apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app
  namespace: staging
spec:
  hosts:
    - app
  http:
    - route:
        - destination:
            host: app
            subset: v1
          weight: 0
        - destination:
            host: app
            subset: v2
          weight: 100
      