apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: eu-west-1
  version: "1.25"
vpc:
  id: "vpc-0626f0c8f75cf4bca"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      eu-west-1a:
          id: "subnet-032b7d50d58ac63e0"
          cidr: "10.0.128.0/20"
      eu-west-1b:
          id: "subnet-0302156c5a4426cfa"
          cidr: "10.0.144.0/20"

managedNodeGroups:
  - name: eks-demo-ng
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    instanceType: t3.medium
    volumeSize: 10
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    labels: {env: dev}
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        cloudWatch: true
  