apiVersion: v1
kind: Pod
metadata:
  name: myapp-1
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
      - name: my-pvc
        mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: mypvc