apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
spec:
  resources:
    requests: 
      storage: 2Gi
  storageClassName: efs
  accessModes:
    - ReadWriteMany
