---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - istio-ingress
  selector:
    matchLabels:
      app: istio-gateway-release
  endpoints:
    - port: metrics
      path: /stats/prometheus